DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO (ID INT AUTO_INCREMENT PRIMARY KEY, NUM_MATRICULA INT NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);



-- para test --
INSERT INTO ODONTOLOGO (NUM_MATRICULA,NOMBRE, APELLIDO) VALUES ('01216','Ana','Zapata');
INSERT INTO ODONTOLOGO (NUM_MATRICULA,NOMBRE, APELLIDO) VALUES ('2312','Juan','Zapata');
INSERT INTO ODONTOLOGO (NUM_MATRICULA,NOMBRE, APELLIDO) VALUES ('2421','Leidy','Zapata');